//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVD.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TE.Core.Properties.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you have selected is not supported.
        /// </summary>
        public static string Biz_Admin_Groups_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Biz_Admin_Groups_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not truncate passenger names without losing details..
        /// </summary>
        public static string Biz_Air_AddTraveler_Max_Length_Validation {
            get {
                return ResourceManager.GetString("Biz_Air_AddTraveler_Max_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A seat has already been selected for {0} {1} on the {2} - {3} flight..
        /// </summary>
        public static string Biz_Air_AlreadyHaveSeatSelection {
            get {
                return ResourceManager.GetString("Biz_Air_AlreadyHaveSeatSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service can no longer be cancelled..
        /// </summary>
        public static string Biz_Air_CannotCancel {
            get {
                return ResourceManager.GetString("Biz_Air_CannotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service cannot use the cryptic emulator..
        /// </summary>
        public static string Biz_Air_CannotUseCryptic {
            get {
                return ResourceManager.GetString("Biz_Air_CannotUseCryptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prices are available for the selected flights, please try another selection..
        /// </summary>
        public static string Biz_Air_NoPricesAvailable {
            get {
                return ResourceManager.GetString("Biz_Air_NoPricesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested invalid flight information. Please check the details provided and try again..
        /// </summary>
        public static string Biz_Air_NoSeatAvailability {
            get {
                return ResourceManager.GetString("Biz_Air_NoSeatAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Information for the flight is not available as entered. Please check the details provided and try again. If the flight is a code-share then please enter all flights before checking for booking class availability..
        /// </summary>
        public static string Biz_Air_NoSeatAvailabilityTryAllSegments {
            get {
                return ResourceManager.GetString("Biz_Air_NoSeatAvailabilityTryAllSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment amounts do not match the total fare for each passenger..
        /// </summary>
        public static string Biz_Air_PaymentAmountDoesNotMatchFares {
            get {
                return ResourceManager.GetString("Biz_Air_PaymentAmountDoesNotMatchFares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected airline does not support seat selection via some channels for this flight. Please attempt seat selection on the airline website..
        /// </summary>
        public static string Biz_Air_SeatMapNotSupported {
            get {
                return ResourceManager.GetString("Biz_Air_SeatMapNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoticketing failed and after-hours ticketing fees are in-effect, confirm if flight should be submitted for ticketing..
        /// </summary>
        public static string Biz_AirModify_AutoTicketingFailed {
            get {
                return ResourceManager.GetString("Biz_AirModify_AutoTicketingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the selected flights are no longer available, please choose new flights and try again..
        /// </summary>
        public static string Biz_AirModify_OneOrMoreFlightsNoLongerAvailable {
            get {
                return ResourceManager.GetString("Biz_AirModify_OneOrMoreFlightsNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is currently disabled.  Please contact an administrator..
        /// </summary>
        public static string Biz_Auth_Login_AccountDisabled {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with the setup of your account. Please contact the administrator (L:001).
        /// </summary>
        public static string Biz_Auth_Login_AccountSetupInvalid {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_AccountSetupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was found in TRAMS however there is an issue bringing your information into TravelEdge ADX. Please contact the system administrator for support. (L:002).
        /// </summary>
        public static string Biz_Auth_Login_ErrorMappingProviderAccountToLocal {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_ErrorMappingProviderAccountToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed - could not validate credentials. Please retry and if you are still encountering a problem, contact your system administrator. (L:003).
        /// </summary>
        public static string Biz_Auth_Login_MembershipAuthenticationFailed {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_MembershipAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with the setup of your account. Please contact the system administrator for support. (L:004).
        /// </summary>
        public static string Biz_Auth_Login_MultipleMatchesOnEmail {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_MultipleMatchesOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with the setup of your account. Please contact the system administrator for support. (L:005).
        /// </summary>
        public static string Biz_Auth_Login_NoMatchOnEmail {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_NoMatchOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with the setup of your account. Please contact the system administrator for support. (L:010).
        /// </summary>
        public static string Biz_Auth_Login_NonPrimaryAgentProfileReturned {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_NonPrimaryAgentProfileReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile can not be created as TRAMS is down. Please contact the system administrator for support. (L:006).
        /// </summary>
        public static string Biz_Auth_Login_ProfileSyncCreateFailedTRAMSUnavailable {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_ProfileSyncCreateFailedTRAMSUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile can not be updated as TRAMS is down. Please contact the system administrator for support. (L:007).
        /// </summary>
        public static string Biz_Auth_Login_ProfileSyncUpdateFailedTRAMSUnavailable {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_ProfileSyncUpdateFailedTRAMSUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deactivated in TRAMS. Please contact the system administrator for support.(L:008).
        /// </summary>
        public static string Biz_Auth_Login_ProviderNoLongerReturnsAccount {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_ProviderNoLongerReturnsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout period for T&amp;C acceptance has expired. Please go back to the login page and try again..
        /// </summary>
        public static string Biz_Auth_Login_TC_UserNotInCache {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_TC_UserNotInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find user. Please contact the system administrator for support.  (L:009).
        /// </summary>
        public static string Biz_Auth_Login_UserNameNotFound {
            get {
                return ResourceManager.GetString("Biz_Auth_Login_UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending the email, please try again later..
        /// </summary>
        public static string Biz_Auth_Reset_CouldNotSendEmail {
            get {
                return ResourceManager.GetString("Biz_Auth_Reset_CouldNotSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the password policy requirements..
        /// </summary>
        public static string Biz_Auth_Reset_PasswordPolicy {
            get {
                return ResourceManager.GetString("Biz_Auth_Reset_PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset link has expired..
        /// </summary>
        public static string Biz_Auth_Reset_TokenExpired {
            get {
                return ResourceManager.GetString("Biz_Auth_Reset_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This companion no longer exists in ClientBase thus updates can not be made..
        /// </summary>
        public static string Biz_Client_CompanionSave_CompanionNoLongerExists {
            get {
                return ResourceManager.GetString("Biz_Client_CompanionSave_CompanionNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientBase is unavailable at this time. Only limited client and companion functionality will be available..
        /// </summary>
        public static string Biz_Client_CompanionSave_ExternalSystemIsDown {
            get {
                return ResourceManager.GetString("Biz_Client_CompanionSave_ExternalSystemIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue saving updates to ClientBase. Not all of your changes may be saved..
        /// </summary>
        public static string Biz_Client_CompanionSave_NonTramsSavingIssue {
            get {
                return ResourceManager.GetString("Biz_Client_CompanionSave_NonTramsSavingIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client needs to be associated with a Family Member before using in aDX. Please ensure in Client Base that the first and last name of the client matches the primary family member..
        /// </summary>
        public static string Biz_Client_NotAvailableDueToBrokenClient {
            get {
                return ResourceManager.GetString("Biz_Client_NotAvailableDueToBrokenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected cabin could not be held, please try again..
        /// </summary>
        public static string Biz_Cruise_HoldFailed {
            get {
                return ResourceManager.GetString("Biz_Cruise_HoldFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Loyalty Number.
        /// </summary>
        public static string Biz_Cruise_Invalid_Loyalty_Number {
            get {
                return ResourceManager.GetString("Biz_Cruise_Invalid_Loyalty_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Service is in Requote state. Please return to the Travel Service page and perform a requote of the cruise travel service..
        /// </summary>
        public static string Biz_Cruise_TravelService_RequoteState {
            get {
                return ResourceManager.GetString("Biz_Cruise_TravelService_RequoteState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cruise does not support this function..
        /// </summary>
        public static string Biz_CruiseLine_Cabin_Availability {
            get {
                return ResourceManager.GetString("Biz_CruiseLine_Cabin_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes to the cruise could not be saved, please try again..
        /// </summary>
        public static string Biz_CruiseModfiy_ModificationFailed {
            get {
                return ResourceManager.GetString("Biz_CruiseModfiy_ModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes to the cruise could not be saved, please try again..
        /// </summary>
        public static string Biz_CruiseModify_SessionExpired {
            get {
                return ResourceManager.GetString("Biz_CruiseModify_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected cruise service has already been booked..
        /// </summary>
        public static string Biz_CruiseService_NotBookable {
            get {
                return ResourceManager.GetString("Biz_CruiseService_NotBookable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid Past Passenger number has been entered. Please go back to the Travel Service Page and make the necessary changes..
        /// </summary>
        public static string Biz_CruiseTravelService_InvalidPastPassengerNumber {
            get {
                return ResourceManager.GetString("Biz_CruiseTravelService_InvalidPastPassengerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process due to invalid data..
        /// </summary>
        public static string Biz_Dev_Examples_BusinessException {
            get {
                return ResourceManager.GetString("Biz_Dev_Examples_BusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the recipients specified. Please check and try again..
        /// </summary>
        public static string Biz_Email_Invalid_Recipient {
            get {
                return ResourceManager.GetString("Biz_Email_Invalid_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation number and booked date are required for Booked services..
        /// </summary>
        public static string Biz_External_MissingBookedDetails {
            get {
                return ResourceManager.GetString("Biz_External_MissingBookedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no airfares available for the selected departure airport..
        /// </summary>
        public static string Biz_FareCode_AirNotAvailable {
            get {
                return ResourceManager.GetString("Biz_FareCode_AirNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected fare code is invalid, please select another one and try again.
        /// </summary>
        public static string Biz_FareCode_Invalid {
            get {
                return ResourceManager.GetString("Biz_FareCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue creating an invoice to track the change in commission. Please try again or contact servicedesk@traveledge.com for assistance..
        /// </summary>
        public static string Biz_Finance_CommissionInvoiceCouldNotBeCreatedCommissionReverted {
            get {
                return ResourceManager.GetString("Biz_Finance_CommissionInvoiceCouldNotBeCreatedCommissionReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reservation has been updated in ClientBase and thus it can no longer be managed from aDX.  Please use ClientBase for the ongoing management of this travel service..
        /// </summary>
        public static string Biz_Finance_Meddling_Agents {
            get {
                return ResourceManager.GetString("Biz_Finance_Meddling_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue updating the reservation and/or creating invoices in ClientBase. Please contact servicedesk@traveledge.com for assistance..
        /// </summary>
        public static string Biz_Finance_Recording_Failed {
            get {
                return ResourceManager.GetString("Biz_Finance_Recording_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card information was specified for at least one of the payment credit cards..
        /// </summary>
        public static string Biz_Invalid_CreditCard {
            get {
                return ResourceManager.GetString("Biz_Invalid_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency has not been provided or is invalid.
        /// </summary>
        public static string Biz_Invalid_Currency {
            get {
                return ResourceManager.GetString("Biz_Invalid_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select filename without special characters in it..
        /// </summary>
        public static string Biz_Invalid_File {
            get {
                return ResourceManager.GetString("Biz_Invalid_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of passengers.
        /// </summary>
        public static string Biz_Invalid_NumOfPassengers {
            get {
                return ResourceManager.GetString("Biz_Invalid_NumOfPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete operation for the quote {0} due to the current quote status: {1}..
        /// </summary>
        public static string Biz_Invalid_Quote_Status {
            get {
                return ResourceManager.GetString("Biz_Invalid_Quote_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total amount from all the credit cards is not equal to the Total in Trip Payment Summary. Please correct it and try again..
        /// </summary>
        public static string Biz_Invalid_TotalInPayment {
            get {
                return ResourceManager.GetString("Biz_Invalid_TotalInPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invoice is not supported for viewing or printing..
        /// </summary>
        public static string Biz_Invoice_NotSupportedByAdxViewer {
            get {
                return ResourceManager.GetString("Biz_Invoice_NotSupportedByAdxViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment with multiple credit cards is unsupported. Please use only one credit card..
        /// </summary>
        public static string Biz_Payments_Amadeus_MultipleCreditCards {
            get {
                return ResourceManager.GetString("Biz_Payments_Amadeus_MultipleCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the entry in the following fields: {0}.
        /// </summary>
        public static string Biz_Payments_Amadeus_ValidationMessages {
            get {
                return ResourceManager.GetString("Biz_Payments_Amadeus_ValidationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing the payment..
        /// </summary>
        public static string Biz_Payments_AmountReceivedUnchanged {
            get {
                return ResourceManager.GetString("Biz_Payments_AmountReceivedUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete operation for the quote {0} due to the current quote status: {1}..
        /// </summary>
        public static string Biz_Payments_BillingDetails_Quote_Status {
            get {
                return ResourceManager.GetString("Biz_Payments_BillingDetails_Quote_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card type was specified for at least one of the payment credit cards. Please specify a valid credit card type for the payment..
        /// </summary>
        public static string Biz_Payments_Invalid_CreditCard {
            get {
                return ResourceManager.GetString("Biz_Payments_Invalid_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was declined or failed due to insufficient funds.
        /// </summary>
        public static string Biz_Payments_PayPal_InsufficientFundsOrDeclined {
            get {
                return ResourceManager.GetString("Biz_Payments_PayPal_InsufficientFundsOrDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified amount is invalid.
        /// </summary>
        public static string Biz_Payments_PayPal_Invalid_Amount {
            get {
                return ResourceManager.GetString("Biz_Payments_PayPal_Invalid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Billing Information is invalid.
        /// </summary>
        public static string Biz_Payments_PayPal_Invalid_BillingInfo {
            get {
                return ResourceManager.GetString("Biz_Payments_PayPal_Invalid_BillingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Credit Card details are invalid.
        /// </summary>
        public static string Biz_Payments_PayPal_Invalid_CreditCard_Information {
            get {
                return ResourceManager.GetString("Biz_Payments_PayPal_Invalid_CreditCard_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Credit Card type is invalid.
        /// </summary>
        public static string Biz_Payments_PayPal_Invalid_CreditCard_Type {
            get {
                return ResourceManager.GetString("Biz_Payments_PayPal_Invalid_CreditCard_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the specified credit cards is an unsupported credit card type..
        /// </summary>
        public static string Biz_Payments_Unsupported_CreditCard {
            get {
                return ResourceManager.GetString("Biz_Payments_Unsupported_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service can no longer be cancelled..
        /// </summary>
        public static string Biz_PlanningFee_CannotCancel {
            get {
                return ResourceManager.GetString("Biz_PlanningFee_CannotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the PNR. Please try again later or contact your administrator to look into the issue closely..
        /// </summary>
        public static string Biz_Pnr_ErrorReadingPnr {
            get {
                return ResourceManager.GetString("Biz_Pnr_ErrorReadingPnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding air to quote, it looks like the price server is down, please try again later. If this issue continues, please contact servicedesk@traveledge.com..
        /// </summary>
        public static string Biz_Quote_AddAir_PassengerPriceBreakdownsMissing {
            get {
                return ResourceManager.GetString("Biz_Quote_AddAir_PassengerPriceBreakdownsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to get the informative pricing for a quote failed. The quote is in invalid status. Please try creating another one..
        /// </summary>
        public static string Biz_Quote_AddCruise_InformativePricingMissing {
            get {
                return ResourceManager.GetString("Biz_Quote_AddCruise_InformativePricingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding cruise to quote, it looks like the price server is down, please try again later. If this issue continues, please contact servicedesk@traveledge.com..
        /// </summary>
        public static string Biz_Quote_AddCruise_PassengerPriceBreakdownsMissing {
            get {
                return ResourceManager.GetString("Biz_Quote_AddCruise_PassengerPriceBreakdownsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue when adding one or more services to your itinerary. Please check the itinerary and retry the missing services..
        /// </summary>
        public static string Biz_Quote_AddingServicesFailed {
            get {
                return ResourceManager.GetString("Biz_Quote_AddingServicesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a fee associated with this request. You need to refresh this page and accept the fee before it can be processed..
        /// </summary>
        public static string Biz_Quote_AgentFeeNotAccepted {
            get {
                return ResourceManager.GetString("Biz_Quote_AgentFeeNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Air Trip does not have any assigned travelers, please assign travelers before booking..
        /// </summary>
        public static string Biz_Quote_AirMissingTravelers {
            get {
                return ResourceManager.GetString("Biz_Quote_AirMissingTravelers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving the air reprice details, please try again or contact support..
        /// </summary>
        public static string Biz_Quote_AirRepriceExpired {
            get {
                return ResourceManager.GetString("Biz_Quote_AirRepriceExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected cabin was successfully released with the cruise provider but failed to update the ADX database. Please proceed with the selection of the new cabin since that action will sync up the cruise service with the provider again..
        /// </summary>
        public static string Biz_Quote_CabinUnHold {
            get {
                return ResourceManager.GetString("Biz_Quote_CabinUnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each existing traveler can only occupy one traveler block..
        /// </summary>
        public static string Biz_Quote_Companions_MultipleProfilesOnSameQuote {
            get {
                return ResourceManager.GetString("Biz_Quote_Companions_MultipleProfilesOnSameQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote copy is not supported with a booked cruise..
        /// </summary>
        public static string Biz_Quote_Copy_NotSupportedPostBook {
            get {
                return ResourceManager.GetString("Biz_Quote_Copy_NotSupportedPostBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new travelers is not supported here. Please select existing travelers and companions or add a new one on the itinerary screen before trying again..
        /// </summary>
        public static string Biz_Quote_Cruise_NewTravelersAddedOnFCONotImplemented {
            get {
                return ResourceManager.GetString("Biz_Quote_Cruise_NewTravelersAddedOnFCONotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote modify is not supported with a booked cruise..
        /// </summary>
        public static string Biz_Quote_Modify_NotSupportedPostBook {
            get {
                return ResourceManager.GetString("Biz_Quote_Modify_NotSupportedPostBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error modifying quote, it looks like the price server is down, please try again later. If this issue continues, please contact servicedesk@traveledge.com..
        /// </summary>
        public static string Biz_Quote_Modify_PassengerPriceBreakdownsMissing {
            get {
                return ResourceManager.GetString("Biz_Quote_Modify_PassengerPriceBreakdownsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers cannot be added or removed to services that have already been booked..
        /// </summary>
        public static string Biz_Quote_PassengersCannotBeAssignedToNonOfferedTravelServices {
            get {
                return ResourceManager.GetString("Biz_Quote_PassengersCannotBeAssignedToNonOfferedTravelServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning fees can not be editied once paid for..
        /// </summary>
        public static string Biz_Quote_PlanningFees_AlreadyPaid {
            get {
                return ResourceManager.GetString("Biz_Quote_PlanningFees_AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning fees can not be editied once the trip has started..
        /// </summary>
        public static string Biz_Quote_PlanningFees_TripHasStarted {
            get {
                return ResourceManager.GetString("Biz_Quote_PlanningFees_TripHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repricing booked quotes with net rate fare code is not allowed.
        /// </summary>
        public static string Biz_Quote_Reprice_BookedNetRateFare {
            get {
                return ResourceManager.GetString("Biz_Quote_Reprice_BookedNetRateFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to re-price the selected quote failed due to inability to provide informative pricing. Original quote pricing was preserved..
        /// </summary>
        public static string Biz_Quote_Reprice_InformativePricingMissing {
            get {
                return ResourceManager.GetString("Biz_Quote_Reprice_InformativePricingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide list of travelers before issuing the re-pricing action.
        /// </summary>
        public static string Biz_Quote_Reprice_MissingTravelers {
            get {
                return ResourceManager.GetString("Biz_Quote_Reprice_MissingTravelers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in finance system failed for the following items: &lt;br/&gt;{0}&lt;br/&gt;Please contact servicedesk@traveledge.com.
        /// </summary>
        public static string Biz_Quote_TMT_TripAndProductsSyncFailed_Format {
            get {
                return ResourceManager.GetString("Biz_Quote_TMT_TripAndProductsSyncFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not have companions on a quote without a contact.
        /// </summary>
        public static string Biz_Quote_Travelers_CompanionsOnQuoteWithoutClient {
            get {
                return ResourceManager.GetString("Biz_Quote_Travelers_CompanionsOnQuoteWithoutClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler updates can not be applied as it affects services that can not be changed. E.g. Ones that are already booked..
        /// </summary>
        public static string Biz_Quote_TravelerUpdate_ValidatingUpdatesAndChangeServiceStatusFailed {
            get {
                return ResourceManager.GetString("Biz_Quote_TravelerUpdate_ValidatingUpdatesAndChangeServiceStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists as a traveler on the quote. Use the companion button to select the existing traveler for this booking..
        /// </summary>
        public static string Biz_Quote_TravelerWithSameNameExists {
            get {
                return ResourceManager.GetString("Biz_Quote_TravelerWithSameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval of detailed price breakdown per traveler failed. Please try again later or with different cabin..
        /// </summary>
        public static string Biz_Quote_UnavailableTravelerPricingBreakdown {
            get {
                return ResourceManager.GetString("Biz_Quote_UnavailableTravelerPricingBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment sent is not sufficient to reconcile the travel service payment discrepancy..
        /// </summary>
        public static string Biz_ReconciliationPayment_PaymentNotSufficient {
            get {
                return ResourceManager.GetString("Biz_ReconciliationPayment_PaymentNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment sent for reconciliation is zero.
        /// </summary>
        public static string Biz_ReconciliationPayment_ZeroAmountPayment {
            get {
                return ResourceManager.GetString("Biz_ReconciliationPayment_ZeroAmountPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprice can not be performed. The cruise travel service is not in booked or deposit state..
        /// </summary>
        public static string Biz_Reprice_InvalidCruiseServiceState {
            get {
                return ResourceManager.GetString("Biz_Reprice_InvalidCruiseServiceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with the communication to TRAMS. Please check your input and contact servicedesk@traveledge.com if you continute to have this problem..
        /// </summary>
        public static string Biz_Trams_ValidationError_Default {
            get {
                return ResourceManager.GetString("Biz_Trams_ValidationError_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enjoy your trip!&lt;/p&gt;
        /// 
        ///&lt;p&gt;If I can be of any further assistance before you travel, please do not hesitate to contact me. 
        ///My email address and phone numbers can be found below.&lt;/p&gt;
        /// 
        ///&lt;p&gt;Kind regards.&lt;/p&gt;.
        /// </summary>
        public static string BonVoyage_Email_Body {
            get {
                return ResourceManager.GetString("BonVoyage_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon Voyage!.
        /// </summary>
        public static string BonVoyage_Email_Subject {
            get {
                return ResourceManager.GetString("BonVoyage_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @media only screen and (max-device-width: 480px)
        ///        {
        ///            body
        ///            {
        ///                width: 100% !important;
        ///            }
        ///            #logo-image
        ///            {
        ///                width: 300px !important;
        ///            }
        ///            #body [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BonVoyage_Email_Template {
            get {
                return ResourceManager.GetString("BonVoyage_Email_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Capturing Authorization failed with the following messages: {0}.
        /// </summary>
        public static string Email_PayPalCaptureFailed_Body_Format {
            get {
                return ResourceManager.GetString("Email_PayPalCaptureFailed_Body_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Capture Authorization Failed.
        /// </summary>
        public static string Email_PayPalCaptureFailed_Subject {
            get {
                return ResourceManager.GetString("Email_PayPalCaptureFailed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADX received a request to reset the password for your
        ///{0} account.
        ///
        ///To reset your password, copy and paste the URL into 
        ///your browser:
        ///{1}
        ///
        ///
        ///_____________________________________________________________________________
        ///
        ///Please do not reply to this message; it was sent from an unmonitored 
        ///email address. This message is a service email related to your use 
        ///of ADX..
        /// </summary>
        public static string Email_ResetPassword_ResetTokenMessage_Body {
            get {
                return ResourceManager.GetString("Email_ResetPassword_ResetTokenMessage_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request.
        /// </summary>
        public static string Email_ResetPassword_ResetTokenMessage_Subject {
            get {
                return ResourceManager.GetString("Email_ResetPassword_ResetTokenMessage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hold for the specified price has expired, please reprice to confirm if the price is still available..
        /// </summary>
        public static string Ex_Air_HoldExpired {
            get {
                return ResourceManager.GetString("Ex_Air_HoldExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized or login timed out.
        /// </summary>
        public static string Ex_Authentication_Default {
            get {
                return ResourceManager.GetString("Ex_Authentication_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to record the information in TMT, please contact your administrator to look into the issue closely..
        /// </summary>
        public static string Ex_Book_TMTSync {
            get {
                return ResourceManager.GetString("Ex_Book_TMTSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to record the information in TMT, please contact your administrator to look into the issue closely..
        /// </summary>
        public static string Ex_Cancel_TMTSync {
            get {
                return ResourceManager.GetString("Ex_Cancel_TMTSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in updating this clients profile in ClientBase. Please try again or contact servicedesk@traveledge.com..
        /// </summary>
        public static string Ex_Clients_SetPrimaryCompanion {
            get {
                return ResourceManager.GetString("Ex_Clients_SetPrimaryCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission information was not retrieved successfully. Please try again or contact servicedesk@traveledge.com .
        /// </summary>
        public static string Ex_Commission_NotRetrieved {
            get {
                return ResourceManager.GetString("Ex_Commission_NotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem in retrieving commission information.
        /// </summary>
        public static string Ex_CommissionService_Default {
            get {
                return ResourceManager.GetString("Ex_CommissionService_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number for this client is already in use..
        /// </summary>
        public static string Ex_Conflict_Clients_PhoneNumberNotUnique {
            get {
                return ResourceManager.GetString("Ex_Conflict_Clients_PhoneNumberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource you are trying to add conflicted with an existing resource.
        /// </summary>
        public static string Ex_Conflict_Default {
            get {
                return ResourceManager.GetString("Ex_Conflict_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a value of {0}. Please choose another..
        /// </summary>
        public static string Ex_Conflict_Dev_ExampleConflictMessage {
            get {
                return ResourceManager.GetString("Ex_Conflict_Dev_ExampleConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have cookies enabled and try again..
        /// </summary>
        public static string Ex_CookieMissing {
            get {
                return ResourceManager.GetString("Ex_CookieMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A custom internal server error.
        /// </summary>
        public static string Ex_Dev_Examples_TravelEdgeException {
            get {
                return ResourceManager.GetString("Ex_Dev_Examples_TravelEdgeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agent&apos;s email was either not found or setup incorrectly. Please contact servicedesk@traveledge.com..
        /// </summary>
        public static string Ex_Email_No_Agent_Email {
            get {
                return ResourceManager.GetString("Ex_Email_No_Agent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF could not be generated. Please try again later..
        /// </summary>
        public static string Ex_Email_No_PDF_Returned {
            get {
                return ResourceManager.GetString("Ex_Email_No_PDF_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged-in agent information is not found or is invalid. Please contact servicedesk@traveledge.com to get your agent profile set up correctly..
        /// </summary>
        public static string Ex_Exception_AgentNotFound {
            get {
                return ResourceManager.GetString("Ex_Exception_AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem identifying the updates to make for this client. Try again by firstly closing the current view and searching for the client..
        /// </summary>
        public static string Ex_Exception_Client_CurrentStateInvalid {
            get {
                return ResourceManager.GetString("Ex_Exception_Client_CurrentStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected cruise line is not supported by the system.
        /// </summary>
        public static string Ex_Exception_CruiseLine_Not_Supported {
            get {
                return ResourceManager.GetString("Ex_Exception_CruiseLine_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation performed is not supported by the selected cruise line operator.
        /// </summary>
        public static string Ex_Exception_CruiseLineOperationNotSupported {
            get {
                return ResourceManager.GetString("Ex_Exception_CruiseLineOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Exception_Default {
            get {
                return ResourceManager.GetString("Ex_Exception_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shore Excursion cannot be removed any more..
        /// </summary>
        public static string Ex_Exception_ExcursionPastOfferedState {
            get {
                return ResourceManager.GetString("Ex_Exception_ExcursionPastOfferedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to persist uploaded file, please try again..
        /// </summary>
        public static string Ex_Exception_FileUpload {
            get {
                return ResourceManager.GetString("Ex_Exception_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from provider, please try again..
        /// </summary>
        public static string Ex_Exception_NoResponseFromProvider {
            get {
                return ResourceManager.GetString("Ex_Exception_NoResponseFromProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment cannot be processed at this time, please try again later or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Exception_Payment_Default {
            get {
                return ResourceManager.GetString("Ex_Exception_Payment_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the provider, please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Exception_ProviderError {
            get {
                return ResourceManager.GetString("Ex_Exception_ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the selected sailing, please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Exception_SailingError {
            get {
                return ResourceManager.GetString("Ex_Exception_SailingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on a selection, please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Exception_SailingMapping {
            get {
                return ResourceManager.GetString("Ex_Exception_SailingMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged-in user information is not found or is invalid..
        /// </summary>
        public static string Ex_Exception_UserNotFound {
            get {
                return ResourceManager.GetString("Ex_Exception_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete &apos;{0}&apos; operation due to internal server error. Please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_GeneralProcessingExceptionInOperation {
            get {
                return ResourceManager.GetString("Ex_GeneralProcessingExceptionInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} identifier.
        /// </summary>
        public static string Ex_Invalid_CodeX {
            get {
                return ResourceManager.GetString("Ex_Invalid_CodeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cruise Travel Service  is invalid.
        /// </summary>
        public static string Ex_Invalid_CruiseTravelService {
            get {
                return ResourceManager.GetString("Ex_Invalid_CruiseTravelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Currency.
        /// </summary>
        public static string Ex_Invalid_Currency {
            get {
                return ResourceManager.GetString("Ex_Invalid_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Summary.
        /// </summary>
        public static string Ex_Invalid_Payment_Summary {
            get {
                return ResourceManager.GetString("Ex_Invalid_Payment_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quote ID is not valid, please try again with a valid quote ID..
        /// </summary>
        public static string Ex_Invalid_Quote {
            get {
                return ResourceManager.GetString("Ex_Invalid_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource does not exist or can not be found.
        /// </summary>
        public static string Ex_NotFound_Default {
            get {
                return ResourceManager.GetString("Ex_NotFound_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process payments. Please try again or contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Payment_Processing_Default {
            get {
                return ResourceManager.GetString("Ex_Payment_Processing_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment completed successfully, however, the data was not fully recorded in the finance system. Please contact servicedesk@traveledge.com.
        /// </summary>
        public static string Ex_Payment_Processing_RecordingToTMTFailed {
            get {
                return ResourceManager.GetString("Ex_Payment_Processing_RecordingToTMTFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record to both Invoice and Vendor Payments completed with errors {0}.
        /// </summary>
        public static string Ex_Payment_Processing_RecordingToTMTFailed_InvoiceAndVendorPayment {
            get {
                return ResourceManager.GetString("Ex_Payment_Processing_RecordingToTMTFailed_InvoiceAndVendorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record to Invoice Payment completed with errors {0}.
        /// </summary>
        public static string Ex_Payment_Processing_RecordingToTMTFailed_InvoicePayment {
            get {
                return ResourceManager.GetString("Ex_Payment_Processing_RecordingToTMTFailed_InvoicePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record to Vendor Payment completed with errors {0}.
        /// </summary>
        public static string Ex_Payment_Processing_RecordingToTMTFailed_VendorPayment {
            get {
                return ResourceManager.GetString("Ex_Payment_Processing_RecordingToTMTFailed_VendorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support ticket was not sent succesfully to the support team, contact servicedesk@traveledge.com..
        /// </summary>
        public static string Ex_SupportTicket_NotCreated {
            get {
                return ResourceManager.GetString("Ex_SupportTicket_NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support ticket for the travel service was not found and not updated in the support ticket system. Please contact servicedesk@traveledge.com..
        /// </summary>
        public static string Ex_SupportTicket_NotFound {
            get {
                return ResourceManager.GetString("Ex_SupportTicket_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support ticket was not updated succesfully to the support team, contact servicedesk@traveledge.com..
        /// </summary>
        public static string Ex_SupportTicket_NotUpdated {
            get {
                return ResourceManager.GetString("Ex_SupportTicket_NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have access to this resource.
        /// </summary>
        public static string Ex_Unauthorized_Default {
            get {
                return ResourceManager.GetString("Ex_Unauthorized_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names of the passengers are too long to be truncated sufficiently to allow the booking process to complete successfully..
        /// </summary>
        public static string Val_Air_NamesTooLong {
            get {
                return ResourceManager.GetString("Val_Air_NamesTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be alphanumeric..
        /// </summary>
        public static string Val_Alphanumeric {
            get {
                return ResourceManager.GetString("Val_Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;br /&gt;Please find attached the quote for your upcoming trip.&lt;br /&gt;&lt;br /&gt;If you have any questions please give me a call.&lt;br /&gt;&lt;br /&gt;Best Regards,&lt;br /&gt;.
        /// </summary>
        public static string Val_Client_Itin_Email {
            get {
                return ResourceManager.GetString("Val_Client_Itin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;br /&gt;Please find attached details for your itinerary.&lt;br /&gt;&lt;br /&gt;If you have any questions please give me a call.&lt;br /&gt;&lt;br /&gt;Best Regards,&lt;br /&gt;.
        /// </summary>
        public static string Val_Client_Itin_Email_Booked {
            get {
                return ResourceManager.GetString("Val_Client_Itin_Email_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is invalid, please enter a correct email address..
        /// </summary>
        public static string Val_Email_Default {
            get {
                return ResourceManager.GetString("Val_Email_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;br /&gt;Please find attached the invoice for your upcoming trip.&lt;br /&gt;&lt;br /&gt;If you have any questions please give me a call.&lt;br /&gt;&lt;br /&gt;Best Regards,&lt;br /&gt;.
        /// </summary>
        public static string Val_Invoice_Email {
            get {
                return ResourceManager.GetString("Val_Invoice_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot exceed {0} characters.
        /// </summary>
        public static string Val_MaxLengthX_Default {
            get {
                return ResourceManager.GetString("Val_MaxLengthX_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        public static string Val_NullInput_Default {
            get {
                return ResourceManager.GetString("Val_NullInput_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between and {1} or {2}.
        /// </summary>
        public static string Val_RangeIntXY_Default {
            get {
                return ResourceManager.GetString("Val_RangeIntXY_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be changed..
        /// </summary>
        public static string Val_ReadOnly {
            get {
                return ResourceManager.GetString("Val_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid, please enter a valid phone number..
        /// </summary>
        public static string Val_RegularExpression_PhoneFormat {
            get {
                return ResourceManager.GetString("Val_RegularExpression_PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a date of birth from January 1, 1914 onwards for all passengers..
        /// </summary>
        public static string Val_Required_BirthYearMin {
            get {
                return ResourceManager.GetString("Val_Required_BirthYearMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future date value is required.
        /// </summary>
        public static string Val_Required_DateFuture {
            get {
                return ResourceManager.GetString("Val_Required_DateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past date value is required.
        /// </summary>
        public static string Val_Required_DatePast {
            get {
                return ResourceManager.GetString("Val_Required_DatePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field.
        /// </summary>
        public static string Val_Required_Default {
            get {
                return ResourceManager.GetString("Val_Required_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are required fields with missing values: {0}.
        /// </summary>
        public static string Val_Required_Default_Provider {
            get {
                return ResourceManager.GetString("Val_Required_Default_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;br /&gt;&lt;br /&gt;Please find attached a catalog outlining the shore excursions available with your cruise.&lt;br /&gt;&lt;br /&gt;We provide a wide variety of exciting, appealing, and enriching shore excursions at prices that are typically lower than those of the cruise lines...&lt;br/&gt;&lt;br/&gt;Excursions sell out quickly - please get in touch with me to reserve your spot.&lt;br /&gt;&lt;br /&gt;Best Regards,&lt;br /&gt;.
        /// </summary>
        public static string Val_ShoreEx_Email {
            get {
                return ResourceManager.GetString("Val_ShoreEx_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to aDX. Please paste the link below into your browser to access the system for the first time: {0}
        ///
        ///(Note: after this first time accessing aDX, you just need to go to https://adx.traveledge.com to log in.)
        ///
        ///You&apos;ll be asked to create a password, and to review and accept the terms and conditions of use for the site, and you are on your way to search and book travel using the world&apos;s #1 agent experience! 
        ///_____________________________________________________________________________
        ///
        ///Please do no [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Welcome_Adx_Email_Body {
            get {
                return ResourceManager.GetString("Welcome_Adx_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to aDX!.
        /// </summary>
        public static string Welcome_Adx_Email_Subject {
            get {
                return ResourceManager.GetString("Welcome_Adx_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for entrusting me with your recent travel arrangements.  I hope that your journey exceeded your expectations and that you had a wonderful time while you were away.&lt;/p&gt;
        /// 
        ///&lt;p&gt;I would appreciate any comments and feedback about the quality of travel services I arranged for you.&lt;/p&gt;
        /// 
        ///&lt;p&gt;I look forward to helping you plan your next trip.&lt;/p&gt;
        /// 
        ///&lt;p&gt;Kind regards.&lt;/p&gt;.
        /// </summary>
        public static string WelcomeHome_Email_Body {
            get {
                return ResourceManager.GetString("WelcomeHome_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Home!.
        /// </summary>
        public static string WelcomeHome_Email_Subject {
            get {
                return ResourceManager.GetString("WelcomeHome_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @media only screen and (max-device-width: 480px)
        ///        {
        ///            body
        ///            {
        ///                width: 100% !important;
        ///            }
        ///            #logo-image
        ///            {
        ///                width: 300px !important;
        ///            }
        ///            #body [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeHome_Email_Template {
            get {
                return ResourceManager.GetString("WelcomeHome_Email_Template", resourceCulture);
            }
        }
    }
}
